# Generated by Django 3.0.3 on 2020-03-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('address', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
