# Generated by Django 3.0.3 on 2020-03-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_findbusiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending',
            name='url',
        ),
        migrations.AddField(
            model_name='trending',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
